### ISSUE TITLE
Extension `monaco-languageclient-project.langium-example` is already registered

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-components#35]
using the react component in vscode mode i am getting this
(on 2nd mount of component)
any idea what could cause this?

is there some destroy/unregister missing?

**Comment by kaisalmen** [comment]
@cdietrich In the meantime I have added explicit disposal of the extension https://github.com/TypeFox/monaco-components/blob/react-python/packages/monaco-editor-wrapper/src/editorAppVscodeApi.ts#L77-L81 but I wasn't able to reproduce your exact issue. Can you provide an example or repo / source link? Thanks

**Comment by cdietrich-everest** [comment]
need to check how easily i can factor out an example. we meanwhile use the monaco classic variant

**Comment by cdietrich** [comment]
need to check how easily i can factor out an example. we meanwhile use the monaco classic variant

**Comment by kaisalmen** [comment]
A unit test here on branch that fails is an idea. Don't know how much boiler-plate code that requires, though. But once in place it will be handy for other react component related tests.

This repo started with unit tests, but we are improving.

**Comment by cdietrich** [comment]
might also be fixed by newer versions already
<img width="1087" alt="Bildschirmfoto 2023-08-31 um 11 21 36" src="https://github.com/TypeFox/monaco-components/assets/238736/237ef034-078f-4b58-9d16-37f3a7412f16">

**Comment by kaisalmen** [comment]
#43 tracks the creation of unit tests for monaco-editor-react.

**Comment by kaisalmen** [comment]
@cdietrich should I transfer this to the other repo? Is it still applicable?

**Comment by cdietrich-everest** [comment]
i dont know. feel free to close.

**Comment by kaisalmen** [comment]
Closing this here. Feel free to open a new issue here: https://github.com/TypeFox/monaco-languageclient if required.
