### ISSUE TITLE
Current Source code repo for monaco-editor-workers

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-components#36]
Hi, where has `monaco-editor-workers` been moved to?

**Comment by kaisalmen** [comment]
See README:
Important: Monaco Editor Workers has been moved to its own [repo](https://github.com/TypeFox/monaco-editor-workers).

**Comment by cdietrich** [comment]
@kaisalmen is that repo intentionally private? am getting 404

**Comment by kaisalmen** [comment]
@cdietrich sorry, I forgot to make it public after extraction and testing that everything works. 🙈
