### ISSUE TITLE
Samples on @typefox/monaco-editor-react": "2.0.0"

### ISSUE THREAD

**Issue by yahorbarkouski** [TypeFox/monaco-components#39]
Hi once again:) Huge sorry for tickets spamming, I'm just curious, do you have any plans for monaco-editor-react 2.0.0 release? I'm playing around language server support for JVM languages ([kotlin example](https://github.com/yahorbarkouski/monaco-components-kotlin/tree/kotlin-language-server-sample)), and just discovered that the latest version of your libs in NPM is 1.1.1 (according to this page: https://www.npmjs.com/package/@typefox/monaco-editor-react), but examples in this repository are already using 2.0.0, so it's a bit complex to follow

**Comment by msujew** [comment]
Taking a look at the [versions tab](https://www.npmjs.com/package/@typefox/monaco-editor-react?activeTab=versions) you will find that there are `next` releases for 2.0 that you can try out. The `monaco-editor-react` package is still being actively maintained and will be released when it's ready.

**Comment by yahorbarkouski** [comment]
My bad, just missed that one! Got it, thank you so much, kind sir!

**Comment by kaisalmen** [comment]
@yahorbarkouski the final release will come once #37 is integrated.

**Comment by yahorbarkouski** [comment]
2.0 next version works already awesome for my case, thank you so much for you work!
