### ISSUE TITLE
MonacoEditorReactComp + registerFileSystemOverlay

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-components#57]
Hi, i am trying to get the `MonacoEditorReactComp` combined with `registerFileSystemOverlay`
in order to have library files available for referencing in the editor.

unfortnately vite/esbuild have problems to bundle it.

any ideas/hints? thanks

```
✘ [ERROR] No matching export in "node_modules/monaco-editor/esm/vs/nls.js" for import "localizeWithPath"

    node_modules/@codingame/monaco-vscode-files-service-override/node_modules/vscode/vscode/src/vs/platform/files/common/io.js:3:9:
      3 │ import { localizeWithPath } from 'monaco-editor/esm/vs/nls.js';
```

https://github.com/cdietrich/my-monaco-editor-react-example/tree/cd/otherFilesExperiments

**Comment by kaisalmen** [comment]
@cdietrich I suspect you have mismatching `monaco-editor` versions. `monaco-editor-workers@0.43.0` depends on `0.43.0` whereas vscode `1.83.x` depends on `0.44.0`.

**Comment by cdietrich** [comment]
Hmm as I use Monaco editor react I don’t have a explicit Monaco version at all

**Comment by cdietrich** [comment]
hmm this is what i did and what does not work

**Comment by kaisalmen** [comment]
@cdietrich strange. That was the only change on fresh check out and `npm run build` completed successfully. Try removing `node_modules` and `package-lock.json` and start fresh.

**Comment by cdietrich** [comment]
hmmm package lock was the problem :(

**Comment by kaisalmen** [comment]
With monaco-languageclient v7 (https://github.com/TypeFox/monaco-languageclient/pull/564) and explicit usage of the treemended monaco-editor package those problems will hopefully go away.

**Comment by kaisalmen** [comment]
@cdietrich new releases are available. treemended monaco-editor is now used everywhere.
