### ISSUE TITLE
Remote LSP server cannot access files

### ISSUE THREAD

**Issue by jadestrong** [TypeFox/monaco-components#60]
<img width="1143" alt="image" src="https://github.com/TypeFox/monaco-components/assets/18475217/94b5ef79-b4e3-4d7c-8697-32802ef22e1f">

Is there a way to solve the problem of remote deployment of pyright-langserver being unable to access source files?

**Comment by kaisalmen** [comment]
Hi @jadestrong sorry I overlooked this question. Does `/workspace` exist on your machine? This example assumes it is there.

**Comment by jadestrong** [comment]
Yes, this directory does not exist. If only the directory exists, it will also prompt that the `python.py` file does not exist, so for each file opened by the editor, it is necessary to create a file with the same name in the workspace directory?

**Comment by kaisalmen** [comment]
But the languageclient passes the content of the open file to the LS, right? So if your are only interested in the content of the editor it should not matter. I will come back with a more solid answer after testing it.

**Comment by jadestrong** [comment]
Yes, if you only open one file, it seems ok, but if you open multiple files and reference each other, it will throw a diagnostic error like this:
![6k9bBSZOKR](https://github.com/TypeFox/monaco-components/assets/18475217/c01f9fc6-5c8d-4dae-812f-a87a5a4ab277)
After the corresponding blank file has been created in the `/workspace` directory , it works fine.
![QuickTime movie](https://github.com/TypeFox/monaco-components/assets/18475217/5cd85078-91a5-4587-8c41-b4d48084bad2)

**Comment by kaisalmen** [comment]
@jadestrong when the pyright runs in vscode the file-creations on the client side are present on the server side directly as they both use the same file system. With this architecture (separated file system of both client and server) you have to ensure this via language server prototcol https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willCreateFiles on your own

**Comment by kaisalmen** [comment]
@jadestrong I will close this issue here as the code moved to https://github.com/TypeFox/monaco-languageclient If you see the need to please open a new issue or discussion there.
