### ISSUE TITLE
Selective applicance of wrappers css

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-components#65]
Hi, is there a way to prevent the monaco editor wrapper messing with the css styling up to the body tag?
e.g. in dark mode "everything" gets dark

**Comment by cdietrich** [comment]
problem seems to be
https://github.com/TypeFox/monaco-languageclient/blob/3979176106da5ff080381252b6a8873cd6e0c150/packages/client/src/monaco-vscode-api-services.ts#L101
as we dont pass a container there.
which leads the body to be the container.

**Comment by kaisalmen** [comment]
Hi @cdietrich that is a result of how `@codingame/monaco-vscode-api` handles this. v2 may change this behavior. https://github.com/TypeFox/monaco-languageclient/pull/600 got delayed, so an already existing fix or new bug fix has to come afterwards. I hope to get PR 600 in finally this week.

**Comment by cdietrich** [comment]
as a workaround i await the wrapper start and then remove the css class from the body and add it to the container of the wrapper.

**Comment by kaisalmen** [comment]
@cdietrich This is fixed in the upcoming version. I will close this issue here, then I don't need to move it over to the other repo.
